### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by RaviVaranasi** [sonar-intellij-plugin/sonar-intellij-plugin#101]
I am running the local analysis with incremental builder option on a large multi module project
```
mvn  sonar:sonar  -Dsonar.analysis.mode=incremental  -Dsonar.host.url=http://sonar_server/    -Dsonar.skipPackageDesign=true
```
I get the following error -

Findbugs output report: project/shared-module/target/sonar/findbugs-result.xml
ERROR 16:33:58.830 > Out of memory
ERROR 16:33:58.830 > Total memory: 129M
ERROR 16:33:58.830 >  free memory: 0M

I have set the MAVEN_OPTS to -Xms256m -Xmx1024m -XX:MaxPermSize=1092m and it works fine from command line. However, when running from intellij, get Out of memory error. Not sure what is different ? Intellij should use the MAVEN_OPTS since the local analysis script is running from command line, right ?

I am using Intellij 14.x version.

**Comment by omayevskiy** [comment]
> Intellij should use the MAVEN_OPTS since the local analysis script is running from command line, right ?

nope currenlty not, you need to setup MAVEN_OPTS again in your script. This is an known issue.
The reason why it does not work like this, is because the plugin does not really run a bash script and also not inside a bash console. It is more low level and just starts a process.

your simplest script could look like:

```
#!/bin/bash
export MAVEN_OPTS="-Xms256m -Xmx1024m -XX:MaxPermSize=1092m"
/path/to/bin/mvn sonar:sonar 
```

**Comment by omayevskiy** [comment]
assuming issue to be solved
